# 数据操作
## 创建张量

In [1]:
import torch

x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


获取张量的形状（沿每个轴的元素数量）

In [2]:
print(x.shape)

torch.Size([12])


获取张量中元素的总数（形状中所有元素的乘积）

In [3]:
print(x.numel())

12


仅仅改变张量的形状，而不改变元素的数量和值
**改变张量的形状，不会改变张量的大小**

In [4]:
X = x.reshape(3, 4)
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [5]:
print(torch.zeros((2, 3, 4)))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
print(torch.ones((2, 3, 4)))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


均值为0，标准差为1的正态分布

In [7]:
print(torch.randn(3, 4))

tensor([[ 0.9428, -1.1350, -0.8976, -0.8036],
        [-0.4587, -0.4411, -0.5509, -0.0547],
        [-1.0873,  0.3921, -1.3750, -0.1604]])


In [8]:
print(torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]))

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


## 运算

In [9]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([ 2.,  4.,  8., 16.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])


求对数的幂运算：$y=e^x$

In [10]:
print(torch.exp(x))

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


In [11]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y), dim=0))  # 沿行（轴0）拼接
print(torch.cat((X, Y), dim=1))  # 沿列（轴1）拼接

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [12]:
print(X == Y)

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])


In [13]:
print(X.sum())

tensor(66.)


广播机制：当对两个形状不同的张量按元素运算时，PyTorch会尝试将它们广播为一个合法的形状（复制每行或每列）

In [15]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
print(a)
print(b)
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


## 索引和切片

In [16]:
print(X)
print(X[-1])
print(X[1:3])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([ 8.,  9., 10., 11.])
tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [17]:
print(X[1, 2])
X[1, 2] = 9
print(X)

tensor(6.)
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])


In [18]:
print(X[0:2, :])
X[0:2, :] = 12
print(X)

tensor([[0., 1., 2., 3.],
        [4., 5., 9., 7.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


## 节省内存

In [19]:
before = id(Y)
Y = Y + X
print(id(Y) == before)

False


In [20]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 139466098308592
id(Z): 139466098308592


In [21]:
before = id(X)
X += Y
print(id(X) == before)

True


## 转换为其他Python对象

In [24]:
A = X.numpy()
B = torch.tensor(A)
print(type(A), type(B))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [25]:
a = torch.tensor([3.5])
print(a, a.item(), float(a), int(a))

tensor([3.5000]) 3.5 3.5 3
